language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003121
before_script:
  - chmod a+x ./build.sh
  - chmod a+x ./deploy.sh
  - cd ./src/TelegramBot.WebApi
script:
  - ./../../build.sh
deploy:
  - provider: script
    script: ./../../deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on:
      branch: master